# Generated by Django 4.1.2 on 2022-10-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_choice_question_id_alter_question_surveys_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('description', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
