# Generated by Django 4.1.2 on 2022-10-15 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(null=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
