# Generated by Django 4.1.2 on 2022-10-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
